ubc_exam_main_homepage:
    path:     /exam
    defaults: { _controller: "UBCExamMainBundle:Default:index" }

exam_upload:
    path:     /exam/upload
    defaults: { _controller: "UBCExamMainBundle:Default:upload" }
    
loggged_in:
    path: /exam/loggedin
    defaults: { _controller: "UBCExamMainBundle:Default:loggedin" }
    
list:
    path: /exam/list
    defaults: { _controller: "UBCExamMainBundle:Default:list" }
    
refresh:
    path: /exam/refresh
    defaults: { _controller: "UBCExamMainBundle:Default:refresh" }
login:
    path: /exam/login
    defaults: { _controller: "UBCExamMainBundle:Default:login" }
delete_exam:
    path: /exam/delete_exam/{examID}
    defaults: { _controller: "UBCExamMainBundle:Default:deleteexam" }
update_exam:
    path: /exam/update_exam/{examID}
    defaults: { _controller: "UBCExamMainBundle:Default:updateexam" }
ubc_exam_logout:
    path: /exam/logout
    defaults: { _controller: "UBCExamMainBundle:Default:login" }