ubc_exam_main_homepage:
    path:     /exam
    defaults: { _controller: "UBCExamMainBundle:Default:index" }

exam_upload:
    path:     /exam/upload
    defaults: { _controller: "UBCExamMainBundle:Default:upload" }
    