parameters:
#    ubc_exam_main.example.class: UBC\Exam\MainBundle\Example
    ubc_exam_main.course_code_inject_listener.class: UBC\Exam\MainBundle\EventListener\CourseInjectionListener
    ubc_exam_main.file_upload_subscriber.class: UBC\Exam\MainBundle\EventListener\FileUploadSubscriber

services:
#    ubc_exam_main.example:
#        class: %ubc_exam_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    ubc.exam.course_code_injection_listener:
        class: %ubc_exam_main.course_code_inject_listener.class%
        arguments: [ @session, @ubc_lt_commons.service.student ]
        tags: [{ name: kernel.event_listener, event: security.interactive_login, method: onLoginSuccess }]
    ubc.exam.file_upload_subscriber:
        class: %ubc_exam_main.file_upload_subscriber.class%
        arguments: [%upload_dir%]
        tags: [{ name: doctrine.event_subscriber, connection: default }]