#!/usr/bin/env bash

GIT_DIR_SAVE=$GIT_DIR ; unset GIT_DIR
GIT_WORK_TREE_SAVE=$GIT_WORK_TREE ; unset GIT_WORK_TREE

if [ ! -f "${OPENSHIFT_DATA_DIR}composer/bin/composer" ]; then
    export COMPOSER_HOME="${OPENSHIFT_DATA_DIR}.composer"
    echo $COMPOSER_HOME > ${OPENSHIFT_HOMEDIR}.env/user_vars/COMPOSER_HOME
    echo "Installing composer"
    curl -s https://getcomposer.org/installer | php -- --install-dir=$OPENSHIFT_DATA_DIR >/dev/null
else
    echo "Updating composer"
    php $OPENSHIFT_DATA_DIR/composer.phar self-update
fi

echo "Running composer install"
cd $OPENSHIFT_REPO_DIR
php $OPENSHIFT_DATA_DIR/composer.phar install

export GIT_DIR=$GIT_DIR_SAVE ; unset GIT_DIR_SAVE
export GIT_WORK_TREE=$GIT_WORK_TREE_SAVE ; unset GIT_WORK_TREE

chmod -R 0777 $OPENSHIFT_REPO_DIR/app/cache
chmod -R 0777 $OPENSHIFT_REPO_DIR/app/logs
