#!/usr/bin/env bash

#GITHUB_API_TOKEN should be defined in the environment variable

GIT_DIR_SAVE=$GIT_DIR ; unset GIT_DIR
GIT_WORK_TREE_SAVE=$GIT_WORK_TREE ; unset GIT_WORK_TREE

if [ ! -f "${OPENSHIFT_DATA_DIR}composer/bin/composer" ]; then
    export COMPOSER_HOME="${OPENSHIFT_DATA_DIR}.composer"
    echo $COMPOSER_HOME > ${OPENSHIFT_HOMEDIR}.env/user_vars/COMPOSER_HOME
    echo "Installing composer"
    curl -s https://getcomposer.org/installer | php -- --install-dir=$OPENSHIFT_DATA_DIR >/dev/null
else
    echo "Updating composer"
    php $OPENSHIFT_DATA_DIR/composer.phar self-update
fi

cd $OPENSHIFT_REPO_DIR
echo "Setup composer config"
php $OPENSHIFT_DATA_DIR/composer.phar config -g github-oauth.github.com $GITHUB_API_TOKEN
echo "Running composer install"
php $OPENSHIFT_DATA_DIR/composer.phar install

export GIT_DIR=$GIT_DIR_SAVE ; unset GIT_DIR_SAVE
export GIT_WORK_TREE=$GIT_WORK_TREE_SAVE ; unset GIT_WORK_TREE

chmod -R 0777 $OPENSHIFT_REPO_DIR/app/cache

php app/console doctrine:schema:update --force
php app/console cache:clear --env=prod
php app/console assetic:dump --env=prod
