imports:
    - { resource: config.yml }
    - { resource: security_internal.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info
        access:
            type: stream
            path:  "%kernel.logs_dir%/access.log"
            channels: [access]
        upload:
            type: stream
            path:  "%kernel.logs_dir%/upload.log"
            channels: [upload]

assetic:
    use_controller: true
    bundles:        [ ]
#swiftmailer:
#    delivery_address: me@example.com

ubc_lt_commons:
  providers:
    xml:
      path: "%kernel.root_dir%/fixtures/"
      serializer: JMS

web_profiler_extra:
    routing:
        enabled:        true
        display_in_wdt: true
    container:
        enabled:        true
        display_in_wdt: true
    assetic:
        enabled:        true
        display_in_wdt: true
    twig:
        enabled:        true
        display_in_wdt: true