imports:
    - { resource: config.yml }
    - { resource: security_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
        only_exceptions: false
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true

web_profiler:
    toolbar: false
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true
    bundles:        [ ]

swiftmailer:
    disable_delivery: true

