imports:
    - { resource: config.yml }
    - { resource: security_in_mem.yml }

framework:
    test: ~
    session:
        #storage_id: session.storage.mock_file
        storage_id: session.storage.filesystem
    profiler:
        collect: false
        only_exceptions: false
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true

web_profiler:
    toolbar: false
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true
    bundles:        [ ]

swiftmailer:
    disable_delivery: true


doctrine:
    dbal:
        default_connection: default

        connections:
            default:
                driver:  pdo_sqlite
                user:    test
                path:    %kernel.root_dir%/cache/test.db
                #memory: true
                charset: utf8
#    orm:
#        entity_managers:
#            default:
#                metadata_cache_driver: apc
#                query_cache_driver:    apc
#                result_cache_driver:   apc

liip_functional_test:
    cache_sqlite_db: true