_ubc_exam_main:
    resource: "@UBCExamMainBundle/Resources/config/routing.yml"

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /exam
        permanent: true

logout:
    path:   /exam/logout