#just place holders....doesn't do anything or at least shouldn't!
ubc_exam_main:
    resource: "@UBCExamMainBundle/Resources/config/routing.yml"
    prefix:   /
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /exam
        permanent: true