security:
    firewalls:
        exam_secured_area:
            pattern:    ^/exam
            anonymous: true
            http_basic: ~
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    access_control:
        - { path: ^/exam/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/exam/download, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/exam/logout, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/exam/list, roles: ROLE_USER }
        - { path: ^/exam/upload, roles: ROLE_USER }
        - { path: ^/exam/delete_exam, roles: ROLE_USER }
        - { path: ^/exam/update_exam, roles: ROLE_USER }
        - { path: ^/exam/user, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
