security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        UBC\Exam\MainBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_STUDENT:     ROLE_USER
        ROLE_STAFF:       ROLE_STUDENT
        ROLE_AMS:         ROLE_STAFF
        ROLE_ADMIN:       [ROLE_AMS]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        exam_secured_area: ~

