security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
#                    jleleu: { password: passworddoesnotmatter, roles: [ 'ROLE_USER'] }
                    
        administrators:
            entity:
                class: UBCExamMainBundle:User
#                property: username
#        ubc_chain_provider:
#            chain:
#                providers: [ in_memory, administrators ]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        ubc_secured_area:
            pattern: ^/exam
            anonymous: ~
            trusted_sso:
                manager: admin_sso
                login_action: false         # BeSimpleSsoAuthBundle:TrustedSso:login
                logout_action: false        # BeSimpleSsoAuthBundle:TrustedSso:logout
                create_users: false
                created_users_roles: [ ROLE_USER ]
                check_path: /exam/loggedin  # created a loggedinAction in DefaultController, but no sure what to do there.

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/exam/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/exam/, roles: ROLE_USER }
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
