security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        UBC\Exam\MainBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        exam_secured_area: ~

    access_control:
        - { path: ^/exam/login, roles: IS_AUTHENTICATED_ANONYMOUSLY } #comment this for cas
        - { path: ^/exam/download, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/exam/loggedin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/exam/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/exam/, roles: ROLE_USER }
        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
