security:
    providers:
        administrators:
            entity:
                class: UBCExamMainBundle:User
    firewalls:
        exam_secured_area:
            pattern:    ^/exam
            anonymous: true
            form_login:
                check_path: login_check
                login_path: exam_login
            logout:
                path:   exam_logout
                target: ubc_exam_main_homepage
