security:
    providers:
        chain_provider:
            chain:
                providers: [in_memory, administrators]
        administrators:
            entity:
                class: UBCExamMainBundle:User
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    firewalls:
        exam_secured_area:
            pattern:    ^/exam
            anonymous: true
            form_login:
                check_path: login_check
                login_path: exam_login
            logout:
                path:   exam_logout
                target: ubc_exam_main_homepage
    access_control:
        - { path: ^/exam/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/exam/download, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/exam/loggedin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/exam/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/exam/list, roles: ROLE_USER }
        - { path: ^/exam/upload, roles: ROLE_USER }
        - { path: ^/exam/delete_exam, roles: ROLE_USER }
        - { path: ^/exam/update_exam, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
