security:
    providers:
        administrators:
            entity:
                class: UBCExamMainBundle:User
    firewalls:
        exam_secured_area:
            pattern:    ^/exam
            anonymous: true
            logout:
                path:   exam_logout
                target: ubc_exam_main_homepage
                success_handler: security.logout.success_handler # uncomment this for cas
            cas:
                cas_server: "%cas_server%"
                cas_port: "%cas_port%"
                cas_path: "%cas_path%"
                ca_cert_path: ~
                cas_protocol: S1
                cas_mapping_attribute: cwlLoginName
                check_path: login_check
                login_path: exam_login

    access_control:
        - { path: ^/exam/login, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/exam/download, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/exam/loggedin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/exam/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/exam/list, roles: ROLE_USER }
        - { path: ^/exam/upload, roles: ROLE_USER }
        - { path: ^/exam/delete_exam, roles: ROLE_USER }
        - { path: ^/exam/update_exam, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
