security:
    providers:
        chain_provider:
            chain:
                providers: [in_memory, administrators]
        administrators:
            entity:
                class: UBCExamMainBundle:User
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
